"""empty message

Revision ID: c660e8ea7645
Revises: c21e6c449089
Create Date: 2021-05-01 00:19:53.041591

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c660e8ea7645'
down_revision = 'c21e6c449089'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###
    op.execute('UPDATE todos set completed=False where completed IS NULL;')
    op.alter_column('todos','completed', nullable=False)

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
